version: '2'
services:
  hub:
    image: selenium/hub:2.53.0
    container_name: selenium-hub
    hostname: selenium-hub.dev
    ports:
      - 4444
    network_mode: bridge

  chrome:
    image: selenium/node-chrome:2.53.0
    container_name: selenium-chrome
    hostname: selenium-chrome.dev
    ports:
      - 5555
    links:
      - hub
    network_mode: bridge